---
title: "DATA413_Project_plan"
format: html
editor: visual
---

## USAID Localization App

This project proposes to analyze USAID contracts and projects spending data from [USASpending.gov](https://www.usaspending.gov/) to analyze the share of USAID funding that goes to local organizations within a country.

### Topic and Data

**Context and Literature Review**

In November 2021, USAID Administrator Samantha Power announced [two ambitious agency wide goals](https://www.usaid.gov/sites/default/files/2023-06/FY%202022%20Localization%20Progress%20Report-June-12-23_vFINAL_1.pdf): "(1) USAID will provide at least a quarter of its program funds directly to local partners by the end of FY 2025, and (2) by 2030, 50 percent of Agency programming will place local communities in the lead to set priorities, co-design projects, drive implementation, and evaluate the impact of its programs."

This commitment to move towards "localization," or the empowerment of local actors in leading and distributing aid, is important for two reasons. First, localization can ameliorate [criticisms](https://www.tandfonline.com/doi/full/10.1080/23311886.2023.2241257) that U.S foreign aid efforts are colonial projects designed either to advance geopolitical interests or to fill the pockets of "beltway bandits." Second, localization can [improve the effectiveness](https://www.cgdev.org/blog/evidence-based-localization-can-existing-evidence-help-guide-usaids-localization-agenda) of aid projects by increasing flexibility, accountability, and contextual knowledge.

Despite these ambitious goals, USAID has provided little in the way of transparent methods to keep track of localization's progress. In fact, USAID's past localization calculations have been [criticized](https://www.devex.com/news/usaid-overestimating-localization-spending-transparency-group-claims-105069) for overestimating shares of local funding. As of October 2023, no methodologically rigorous localization analysis has been made for USAID contracts and grants that has both wide geographic and temporal coverage.

**Data Source**

To analyze aid localization, this project will use the [USASpending api](https://api.usaspending.gov/) to pull contracts and grants level data for USAID (filtering by agency = USAID).

The dataset contains roughly 70,000 USAID grants and contracts from 1998 to the present. The USASpending database is updated frequently with new contracts and grants information and is frequently updated by USAID in compliance with the [Federal Funding Accountability and Transparency Act](https://www.usaid.gov/partner-with-us/resources-for-partners/usaid-partners).

Variables of particular interest are total_obligated_amount, primary_place_of_performance_country_code, and recipient_country_code along with contract_date and fiscal year.  Top level contracts data from the api could potentially be joined with a separate pull of subaward data to provide a more granular analysis which encompasses subaward data.

### Use Case

This project is aimed towards development professionals, academics, members of NGO’s (especially those categorized as local), and interested members of the public. As there is not currently an easily accessible tool to analyze where USAID recipient orgs are based, this app will help users gain a clear top-level understand of USAID localization trends in a given country.

Potential questions of interest include:
  -What percentage of US aid to a given country is going to local organizations?
  -Has the proportion of local funding trended upwards or downwards over time?
  -What are the largest local and non-local recipients of funding in a given country.

### Ethical Review

Given that our data is from a public facing government database, there are limited ethical issues in terms of data privacy and sourcing. Our data source demonstrates strong alignment with the best practices set worth by the OECD's [Good Practice Principles for Data Ethics in the Public Sector](https://www.oecd.org/digital/digital-government/good-practice-principles-for-data-ethics-in-the-public-sector.htm) by specifying the data's use and publishing open source data.  Our project can stay in alignment with these standards by releasing clearly documented open source code and increasing the accessibility of our project (i.e. through minimizing technical jargon).

Throughout the life cycle of our project, our group will work to ensure that our findings are specific and clearly defined.  This is to limit the ability for our project's data to be cherry picked by politicians or interest groups, a potential ethical issue which we identified. By working to ensure that our outputs are clear and designed to minimize statistical misrepresentation (e.g. removing options for trend lines when they would not be appropriate) we can limit the potential for our data to be misrepresented by unethical actors.

### App Concept

### Collaboration
