---
title: "plan_update"
format: html
editor: visual
---

## Project Plan Update

Nick C, Kento H, Orion F, Tristan L. Data-412 (all members)

### Update on context/problem

To better refine our use case, we consulted with researchers from American University's Accountability Research Center who specialize in foreign aid flow. Based on that conversation, minimal revisions on our projects context and problem are required. In terms of use case, it was suggested that there is currently a far bigger focus on prime awards by researchers and development professionals as opposed to sub-awards. Thus, we have decided to prioritize creating a clear analysis of prime award localization as a minimal viable product before analyzing sub-awards.

### Ethical Review

There are minimal updates regarding our ethical review. Given that we are dealing with open source government data which has already been redacted to eliminate any safety/privacy issues, we are confident that our project has no major ethical concerns.

As discussed in the initial project plan, our group has continued discussing how to prevent the misrepresentation of our data. This means that we have taken measures such as drafting text for an into tab which details the limitations of our data set.

### Progress on Data Sourcing and Cleaning:

Our proposed data source of USASpending.gov USAID awards data remains the same. We have two main functions in our .R file which focus on data sourcing, cleaning, and tidying:

API Functionality (func_call_api.R): A framework has been established for the function that will handle API requests to USASpending. The next step will be to complete the logic necessary to obtain the data. This will be additional functionality added after we have a minimila viable product.

Data Cleaning (func_clean_df.R): We created a strong data cleansing tool to handle raw data from contracts and grants. It guarantees that column names are consistent across data sets, combines the data into a single frame, and uses country codes to distinguish between local and non-local awards. It also corrects country code inconsistencies.

### Progress on Application Development (app.R):

Our finalized app layout with contain two tabs:

One of the tabs accessible in the Shiny app will be a world map. This was part of our original plan, but has been expanded upon. The current plan is to create an interface wherein the user is presented with a map of the world, and when they click on one of its countries they are given a breakdown of the relevant data for said country.

The second tab will contain a stacked bar chart and scatter plot which contain overall summary data for global localization. The stacked bar chart will fill based on a boolean indicator of local funding (local vs non local) with aid in USD for the y-axis and fiscal year for the x axis. The scatter plot will plot localization percentages vs total aid, filling by continent with pop-up labels for country name.

### User options

Our project contains minimal revisions in terms of user data manipulation and graphical analysis. We still plan on allowing users to filter based on country, fiscal year, local vs non-local funding and award type (contract vs grant). All refinements of user visualization options are discussed above.

In terms of statistical analysis, we have considered allowing users to conduct some form of bivariate analysis on individual awards data to analyze what factors impact a countries localization percentage. Given that this is not a required component of the project and the fact that potential app users seem more interested in clear visualizations of the data, we will add this feature only after having a minimally viable product.

### Risk Assesment

Potential risks to completion included failing to create a  sufficiently clean data set in a reasonable time to allow for work on other project module and a failure for individual standalone app modules to integrate into the final product.

To mitigate the first problem, we have used a csv of sample data to develop a data cleaning function which allows for work on all other app features.  Our minimal viable product will be based on this sample data set, only integrating an API if there is sufficient time.

Similarly, we have refined our development approach to focus on collectively creating a minimal viable product instead of standalone modules which don't necessarily work together.  Our new development approach prioritizes essential features which eliminates the risks associated with non-compatability of app modules.

### Outline

Data cleaning and gathering (completed) - Nick\
App design and UI, user selection options - Nick: (11/20) 3 Hours\
Mapping tab - Orion: (12/1) 5 hours\
Graphing tab - Kento and Tristan: (12/1) 5 hours\
Optional features after MVP \
API (Nick)\
Interactive map pins (Orion)\
Subaward Integration\
Presentation rehearsal: (12/9)\
Vignette (Tristan, Kento, Orion): (12/9)
