tags$div(
  tags$br(),
  h1("USAID Localization Dashboard: FY2020-2022"),
  tags$p("This dashboard visualizes USAID Localization Data from FY2020 - FY2022. The app's scoping (FY2020-2022) is based on all publicly available USAID data with USAID's self-reported localization determination. “Localization” in this app refers to", a("direct local funding", href = "https://www.usaid.gov/sites/default/files/2023-04/Key-Performance-Indicators-Direct-AA-Funding-Localization.pdf", target="_blank"), "— as defined by USAID. Figures and descriptive data pull from publicly available materials related to USAID’s initiative to increase agency-wide direct funding to ‘local’ organizations to", a("25% of all funding by 2025.", href = "https://www.usaid.gov/news-information/speeches/nov-04-2021-administrator-samantha-power-new-vision-global-development", target="_blank")),
  tags$p("To use the app, first select a country(s) and then navigate to one of the tab's described below."),
  h2("App Tab Descriptions"),
  tags$p(strong("USAID Self-Reported Localization Shares:"), "USAID direct local funding shares differentiated by USAID’s determination of ‘local’ and ‘non-local’ recipients."),
  tags$p(strong("Funding Obligations by Country:"), "Total USAID project funding obligations for selected country(s) and fiscal year(s)."),
  tags$p(strong("Project Count by Country:"), "Total count of USAID projects by localization status for selected country(s) and fiscal year(s). Total projects are counted for each fiscal year. For instance, a project receiving funding in FY2020 and FY2021 counts toward the total of both fiscal years."),
  tags$p(strong("Top 10 Projects:"), "Top 10 Projects by total obligations across selected fiscal year(s).  Hover over the bars for project details."),
  tags$p(strong("Project Data:"), "Data table with descriptive and financial project information for selected country(s) and fiscal years(s)", strong("combined across selected years."), "‘Activity Names’ are sourced from ForeignAssistance.gov by using Activity IDs, given missing descriptive data in USAID's FY2020-2022 Localization Source Data. Some Activity IDs could not be matched resulting in \"Not Listed\" under the \"Activity Name\" of certain projects."),
  tags$p(strong("Project Data Separated by Fiscal Year:"), "Data table with descriptive and financial project information for selected country(s) and fiscal years(s)", strong("separated by fiscal year."), "‘Activity Names’ are sourced from ForeignAssistance.gov by using Activity IDs, given missing descriptive data in USAID's FY2020-2022 Localization Source Data. Some Activity IDs could not be matched resulting in \"Not Listed\" under the \"Activity Name\" of certain projects."),
  tags$p(strong("Recipient Data:"), "Data table listing total funding obligations and project count by implementing partner for selected country(s) and fiscal year(s). 'Project Counts' are the sum of unique projects an implementing partner has managed across the selected fiscal year(s). For instance, a project receiving funding in FY2020 and FY2021 would only be counted once."),
  h2("Sidebar Guide"),
  tags$p(strong("Select Country:"), "Selects countries covered by graph and table tabs.  Default setting displays graphs from selected countries side by side."),
  tags$p(strong("Year Select:"), "Selects year(s) covered by graph and table tabs."),
  tags$p(strong("Aggregate Countries:"), "If checked, combines data from all countries into a single graph (as opposed to multiple side-by-side graphs)."),
  tags$p(strong("Data Download Buttons:"), "\"Project Data Table\", \"Project Data by FY\", and \"Recipient Data Table\" buttons download CSV copies of data displayed in the corresponding app tabs.  \"Download Source Data\" button downloads unfiltered dataset across all countries and fiscal years."),
  h2("Source Data"),
  a("Moving Toward a Model of Locally Led Development: FY 2022 Localization Progress Report", href = "https://www.usaid.gov/localization/measurement", target="_blank"),
  tags$br(),
  a("USAID Localization FY2020-2022 Source Data", href = "https://www.usaid.gov/sites/default/files/2023-06/USAID-FY20-FY22-Local-Funding-Public-Report-2023_04Apr_25.xlsx", target="_blank"),
  tags$br(),
  tags$br(),
  strong("Author Contact: nc5628a@american.edu"),
  tags$br(),
  strong("Designed by: Nicholas Chen"),
  tags$br(),
  tags$span("For more analysis of USAID's localization and locally-led development initiative, visit Accountability Research Center’s", a(" Locally-Led Development and Open Government: Focus on USAID", href = "https://accountabilityresearch.org/usaid-locally-led-development-open-government/", target="_blank"), "page."),
  tags$br(),
  a("Twitter: @AcctResearchCtr", href = "https://twitter.com/AcctResearchCtr?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor", target="_blank"),
  tags$br(),
  tags$p(a("Facebook: facebook.com/AcctResearchCtr/", href = "https://www.facebook.com/AcctResearchCtr/", target="_blank")),
)
