---
title: "DATA413_Project_plan"
format: html
editor: visual
---

## USAID Localization App

This project proposes to analyze USAID contracts and projects spending data from [USASpending.gov](https://www.usaspending.gov/) to analyze the share of USAID funding that goes to local organizations within a country.

### Topic and Data

**Context and Literature Review**

In November 2021, USAID Administrator Samantha Power announced [two ambitious agency wide goals](https://www.usaid.gov/sites/default/files/2023-06/FY%202022%20Localization%20Progress%20Report-June-12-23_vFINAL_1.pdf): "(1) USAID will provide at least a quarter of its program funds directly to local partners by the end of FY 2025, and (2) by 2030, 50 percent of Agency programming will place local communities in the lead to set priorities, co-design projects, drive implementation, and evaluate the impact of its programs."

This commitment to move towards "localization," or the empowerment of local actors in leading and distributing aid, is important for two reasons. First, localization can ameliorate [criticisms](https://www.tandfonline.com/doi/full/10.1080/23311886.2023.2241257) that U.S foreign aid efforts are colonial projects designed either to advance geopolitical interests or to fill the pockets of "beltway bandits." Second, localization can [improve the effectiveness](https://www.cgdev.org/blog/evidence-based-localization-can-existing-evidence-help-guide-usaids-localization-agenda) of aid projects by increasing flexibility, accountability, and contextual knowledge.

Despite these ambitious goals, USAID has provided little in the way of transparent methods to keep track of localization's progress. In fact, USAID's past localization calculations have been [criticized](https://www.devex.com/news/usaid-overestimating-localization-spending-transparency-group-claims-105069) for overestimating shares of local funding. As of October 2023, no methodologically rigorous localization analysis has been made for USAID contracts and grants that has both wide geographic and temporal coverage.

**Data Source**

To analyze aid localization, this project will use the [USASpending api](https://api.usaspending.gov/) to pull contracts and grants level data for USAID (filtering by agency = USAID).

The dataset contains roughly 70,000 USAID grants and contracts from 1998 to the present. The USASpending database is updated frequently with new contracts and grants information and is frequently updated by USAID in compliance with the [Federal Funding Accountability and Transparency Act](https://www.usaid.gov/partner-with-us/resources-for-partners/usaid-partners).

Variables of particular interest are total_obligated_amount, primary_place_of_performance_country_code, and recipient_country_code along with contract_date and fiscal year. Top level contracts data from the api will be joined with a separate api call to enable a more granular analysis which encompasses subaward data.

### Use Case

This project is aimed towards development professionals, academics, members of NGO's (especially those categorized as local), and interested members of the public. As there is not currently an easily accessible tool to analyze where USAID recipient organizations are based, this app will help users gain a clear top-level understand of USAID localization trends in a given country.

Potential questions of interest include:\

-What percentage of US aid to a given country is going to local organizations?\

-Has the proportion of local funding trended upwards or downwards over time?\

-What are the largest local and non-local recipients of funding in a given country?

Anticipated workflow of uers is as follows. User will begin by selecting a country and year(s) of interest. Based on these filters, user will be able to view a map which displays the country of origin for all recipient organizations conducting projects in selected country for all year(s) of interest. Second tab will display a stacked bar showing percentage of local and non-local funding. User workflow is designed to minimize technical barriers-no data selection is required.

### Ethical Review

Given that our data is from a public facing government database, there are limited ethical issues in terms of data privacy and sourcing. Our data source demonstrates strong alignment with the best practices set worth by the OECD's [Good Practice Principles for Data Ethics in the Public Sector](https://www.oecd.org/digital/digital-government/good-practice-principles-for-data-ethics-in-the-public-sector.htm) by specifying the data's use and publishing open source data. Our project can stay in alignment with these standards by releasing clearly documented open source code and increasing the accessibility of our project (i.e. through minimizing technical jargon).

Throughout the life cycle of our project, our group will work to ensure that our findings are specific and clearly defined. This is to limit the ability for our project's data to be cherry picked by politicians or interest groups, a potential ethical issue which we identified. By working to ensure that our outputs are clear and designed to minimize statistical misrepresentation (e.g. removing options for trend lines when they would not be appropriate) we can limit the potential for our data to be misrepresented by unethical actors.

### App Concept

Our app's functionality can be divided into the following modules: data sourcing, data cleaning, graphing and mapping, and the shiny app UI + wrapper.

**Data Sourcing** The project will pull data on USAID grants (primary awards) and subawards using the USASpending API. We are considering making a rough interface to manually input CSV while we are figuring out the API, but the final product will utilize the API so that it stays up to date.

**Data Cleaning** The data will be cleaned to remove duplicates and other issues, and then the subawards will be joined to the primary awards so that they can be compared. Some combination of group_by and pivot longer will be used to append the total value and count of sub awards to each primary contract to ensure that obligations are not double counted under a primary contract and subaward. Our analysis of the data will focus on (but not necessarily be limited to) whether grants intended to aid a given country are carried out through a firm local to said country or through an external (usually American) firm.

(Since we are all 413 students the statistical analysis tab will be replaced with the country level stacked bar of aid by year)

**Graphing and Mapping** Once processed, data will be piped into an interactive map if possible. On this map, users will select a country in order to see a breakdown of its aid. This will include whether awards went to local sources. If a map cannot be arranged, our backup plan is to create a more standard user interface where countries are selected from a searchable list. We greatly prefer the map option, however, as it will look cleaner and be more accessible to laymen. Furthermore, using a world map to display our data has the potential to lead to as of yet unconsidered analysis opportunities if the project moves ahead of schedule. We will also provide a stacked bar plot which will display the proportion and dollar amount of local and non-local aid to a given country. For both plots, users will be able to select a date range (by year) and recipient country.

**Shiny App Wrapper** Following the best practices of app design, we intend for the majority of the above three modules to take place in functions which can be called in the business logic section of our app (or in reactive functions in the case of the graphing functions). Our shiny app will contain multiple tabs to delineate specific app functions along with a intro tab describing our project and data sources, a methods tab which verbally describes our method of analysis, and a data table tab which displays the data piped into our graphs.

### Collaboration

Group Member Names: Nicholas Chen, Tristan Lichter, Orion Freed, Kento Horimai

Our team will follow a "Shared Repository" workflow model where we will create and write to branches based on each major module of our project (e.g. a api branch, data cleaning branch, etc). We deemed this approach most efficient given the small size of our team and the ability to compartmentalize our app's functionality. Branches will be merged with main only after a discussion with all team members.

**Rough Schedule**\
API Function: 11/9 - Nick\
Data Cleaning and Exploratory Analysis: 11/17 - Tristan + Kento\
Progress Report: Orion\
Map: 11/24 (start with placeholder data) Orion\
Country level stacked bar: 11/24 Kento\
Shiny wrapper: 12/7: all group members\
Finishing touches and intro and methodology: all group members\
Vignette: Tristan + Nick\

Major phases and milestones have dates next to them. While data cleaning and API call is being written, other group members will use manually exported csv to write/test functions.
